//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductExtra.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        public int ProductId { get; set; }
        [Required(ErrorMessage="Product Name Cannot Be Empty")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Product Category Cannot Be Empty")]
        public string Category { get; set; }
        [Required(ErrorMessage = "Product Price Cannot Be Empty")]
        public string Price { get; set; }
        [Required(ErrorMessage = "Product Quantity Cannot Be Empty")]
        public int Quantity { get; set; }
        [Required(ErrorMessage = "Product Description Be Empty")]
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        [Required(ErrorMessage = "Product Image Cannot Be Empty")]
        public string SmallImage { get; set; }
        public string LargeImage { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public HttpPostedFileBase ImageFile1 { get; set; }

    }
}
